spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
